onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - vue-demi

patchedDependencies:
  valaxy@0.25.9: patches/valaxy@0.25.9.patch
  valaxy-theme-press@0.25.9: patches/valaxy-theme-press@0.25.9.patch
